// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Version.proto

package mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf;

public final class VersionProtos
{
	private VersionProtos() {}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry ) {}

	public interface VersionRequestOrBuilder extends
			com.google.protobuf.MessageOrBuilder
	{
	}

	/**
	 * Protobuf type {@code VersionRequest}
	 */
	public static final class VersionRequest extends
			com.google.protobuf.GeneratedMessage implements
			VersionRequestOrBuilder
	{
		// Use VersionRequest.newBuilder() to construct.
		private VersionRequest(
				com.google.protobuf.GeneratedMessage.Builder<?> builder ) {
			super(
					builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private VersionRequest(
				boolean noInit ) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final VersionRequest defaultInstance;

		public static VersionRequest getDefaultInstance() {
			return defaultInstance;
		}

		public VersionRequest getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private VersionRequest(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!parseUnknownField(
									input,
									unknownFields,
									extensionRegistry,
									tag)) {
								done = true;
							}
							break;
						}
					}
				}
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			}
			finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.internal_static_VersionRequest_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.internal_static_VersionRequest_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest.class,
							mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest.Builder.class);
		}

		public static com.google.protobuf.Parser<VersionRequest> PARSER = new com.google.protobuf.AbstractParser<VersionRequest>() {
			public VersionRequest parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry )
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new VersionRequest(
						input,
						extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<VersionRequest> getParserForType() {
			return PARSER;
		}

		private void initFields() {}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(
				com.google.protobuf.CodedOutputStream output )
				throws java.io.IOException {
			getSerializedSize();
			getUnknownFields().writeTo(
					output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		@java.lang.Override
		public boolean equals(
				final java.lang.Object obj ) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest)) {
				return super.equals(obj);
			}
			mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest other = (mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest) obj;

			boolean result = true;
			result = result && getUnknownFields().equals(
					other.getUnknownFields());
			return result;
		}

		private int memoizedHashCode = 0;

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptorForType().hashCode();
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest parseFrom(
				com.google.protobuf.ByteString data )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(
					data,
					extensionRegistry);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest parseFrom(
				byte[] data )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(
					data,
					extensionRegistry);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest parseFrom(
				java.io.InputStream input )
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			return PARSER.parseFrom(
					input,
					extensionRegistry);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest parseDelimitedFrom(
				java.io.InputStream input )
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(
					input,
					extensionRegistry);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest parseFrom(
				com.google.protobuf.CodedInputStream input )
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			return PARSER.parseFrom(
					input,
					extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest prototype ) {
			return newBuilder().mergeFrom(
					prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent ) {
			Builder builder = new Builder(
					parent);
			return builder;
		}

		/**
		 * Protobuf type {@code VersionRequest}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequestOrBuilder
		{
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.internal_static_VersionRequest_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.internal_static_VersionRequest_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest.class,
								mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest.Builder.class);
			}

			// Construct using
			// mil.nga.giat.geowave.datastore.hbase.query.protobuf.VersionProtos.VersionRequest.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent ) {
				super(
						parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(
						buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.internal_static_VersionRequest_descriptor;
			}

			public mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest getDefaultInstanceForType() {
				return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest
						.getDefaultInstance();
			}

			public mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest build() {
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest buildPartial() {
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest result = new mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest(
						this);
				onBuilt();
				return result;
			}

			public Builder mergeFrom(
					com.google.protobuf.Message other ) {
				if (other instanceof mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest) {
					return mergeFrom((mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest) other);
				}
				else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest other ) {
				if (other == mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest
						.getDefaultInstance()) return this;
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry )
					throws java.io.IOException {
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(
							input,
							extensionRegistry);
				}
				catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest) e
							.getUnfinishedMessage();
					throw e;
				}
				finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			// @@protoc_insertion_point(builder_scope:VersionRequest)
		}

		static {
			defaultInstance = new VersionRequest(
					true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:VersionRequest)
	}

	public interface VersionResponseOrBuilder extends
			com.google.protobuf.MessageOrBuilder
	{

		// repeated string versionInfo = 1;
		/**
		 * <code>repeated string versionInfo = 1;</code>
		 */
		java.util.List<java.lang.String> getVersionInfoList();

		/**
		 * <code>repeated string versionInfo = 1;</code>
		 */
		int getVersionInfoCount();

		/**
		 * <code>repeated string versionInfo = 1;</code>
		 */
		java.lang.String getVersionInfo(
				int index );

		/**
		 * <code>repeated string versionInfo = 1;</code>
		 */
		com.google.protobuf.ByteString getVersionInfoBytes(
				int index );
	}

	/**
	 * Protobuf type {@code VersionResponse}
	 */
	public static final class VersionResponse extends
			com.google.protobuf.GeneratedMessage implements
			VersionResponseOrBuilder
	{
		// Use VersionResponse.newBuilder() to construct.
		private VersionResponse(
				com.google.protobuf.GeneratedMessage.Builder<?> builder ) {
			super(
					builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private VersionResponse(
				boolean noInit ) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final VersionResponse defaultInstance;

		public static VersionResponse getDefaultInstance() {
			return defaultInstance;
		}

		public VersionResponse getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private VersionResponse(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!parseUnknownField(
									input,
									unknownFields,
									extensionRegistry,
									tag)) {
								done = true;
							}
							break;
						}
						case 10: {
							if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
								versionInfo_ = new com.google.protobuf.LazyStringArrayList();
								mutable_bitField0_ |= 0x00000001;
							}
							versionInfo_.add(input.readBytes());
							break;
						}
					}
				}
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			}
			catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			}
			finally {
				if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
					versionInfo_ = new com.google.protobuf.UnmodifiableLazyStringList(
							versionInfo_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.internal_static_VersionResponse_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.internal_static_VersionResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse.class,
							mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse.Builder.class);
		}

		public static com.google.protobuf.Parser<VersionResponse> PARSER = new com.google.protobuf.AbstractParser<VersionResponse>() {
			public VersionResponse parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry )
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new VersionResponse(
						input,
						extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<VersionResponse> getParserForType() {
			return PARSER;
		}

		// repeated string versionInfo = 1;
		public static final int VERSIONINFO_FIELD_NUMBER = 1;
		private com.google.protobuf.LazyStringList versionInfo_;

		/**
		 * <code>repeated string versionInfo = 1;</code>
		 */
		public java.util.List<java.lang.String> getVersionInfoList() {
			return versionInfo_;
		}

		/**
		 * <code>repeated string versionInfo = 1;</code>
		 */
		public int getVersionInfoCount() {
			return versionInfo_.size();
		}

		/**
		 * <code>repeated string versionInfo = 1;</code>
		 */
		public java.lang.String getVersionInfo(
				int index ) {
			return versionInfo_.get(index);
		}

		/**
		 * <code>repeated string versionInfo = 1;</code>
		 */
		public com.google.protobuf.ByteString getVersionInfoBytes(
				int index ) {
			return versionInfo_.getByteString(index);
		}

		private void initFields() {
			versionInfo_ = com.google.protobuf.LazyStringArrayList.EMPTY;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1) return isInitialized == 1;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(
				com.google.protobuf.CodedOutputStream output )
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < versionInfo_.size(); i++) {
				output.writeBytes(
						1,
						versionInfo_.getByteString(i));
			}
			getUnknownFields().writeTo(
					output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1) return size;

			size = 0;
			{
				int dataSize = 0;
				for (int i = 0; i < versionInfo_.size(); i++) {
					dataSize += com.google.protobuf.CodedOutputStream.computeBytesSizeNoTag(versionInfo_
							.getByteString(i));
				}
				size += dataSize;
				size += 1 * getVersionInfoList().size();
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		@java.lang.Override
		public boolean equals(
				final java.lang.Object obj ) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse)) {
				return super.equals(obj);
			}
			mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse other = (mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse) obj;

			boolean result = true;
			result = result && getVersionInfoList().equals(
					other.getVersionInfoList());
			result = result && getUnknownFields().equals(
					other.getUnknownFields());
			return result;
		}

		private int memoizedHashCode = 0;

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptorForType().hashCode();
			if (getVersionInfoCount() > 0) {
				hash = (37 * hash) + VERSIONINFO_FIELD_NUMBER;
				hash = (53 * hash) + getVersionInfoList().hashCode();
			}
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse parseFrom(
				com.google.protobuf.ByteString data )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(
					data,
					extensionRegistry);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse parseFrom(
				byte[] data )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(
					data,
					extensionRegistry);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse parseFrom(
				java.io.InputStream input )
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			return PARSER.parseFrom(
					input,
					extensionRegistry);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse parseDelimitedFrom(
				java.io.InputStream input )
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(
					input,
					extensionRegistry);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse parseFrom(
				com.google.protobuf.CodedInputStream input )
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			return PARSER.parseFrom(
					input,
					extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse prototype ) {
			return newBuilder().mergeFrom(
					prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent ) {
			Builder builder = new Builder(
					parent);
			return builder;
		}

		/**
		 * Protobuf type {@code VersionResponse}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponseOrBuilder
		{
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.internal_static_VersionResponse_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.internal_static_VersionResponse_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse.class,
								mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse.Builder.class);
			}

			// Construct using
			// mil.nga.giat.geowave.datastore.hbase.query.protobuf.VersionProtos.VersionResponse.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent ) {
				super(
						parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				versionInfo_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(
						buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.internal_static_VersionResponse_descriptor;
			}

			public mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse getDefaultInstanceForType() {
				return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse
						.getDefaultInstance();
			}

			public mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse build() {
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse buildPartial() {
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse result = new mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse(
						this);
				int from_bitField0_ = bitField0_;
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					versionInfo_ = new com.google.protobuf.UnmodifiableLazyStringList(
							versionInfo_);
					bitField0_ = (bitField0_ & ~0x00000001);
				}
				result.versionInfo_ = versionInfo_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(
					com.google.protobuf.Message other ) {
				if (other instanceof mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse) {
					return mergeFrom((mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse) other);
				}
				else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse other ) {
				if (other == mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse
						.getDefaultInstance()) return this;
				if (!other.versionInfo_.isEmpty()) {
					if (versionInfo_.isEmpty()) {
						versionInfo_ = other.versionInfo_;
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					else {
						ensureVersionInfoIsMutable();
						versionInfo_.addAll(other.versionInfo_);
					}
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry )
					throws java.io.IOException {
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(
							input,
							extensionRegistry);
				}
				catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse) e
							.getUnfinishedMessage();
					throw e;
				}
				finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// repeated string versionInfo = 1;
			private com.google.protobuf.LazyStringList versionInfo_ = com.google.protobuf.LazyStringArrayList.EMPTY;

			private void ensureVersionInfoIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					versionInfo_ = new com.google.protobuf.LazyStringArrayList(
							versionInfo_);
					bitField0_ |= 0x00000001;
				}
			}

			/**
			 * <code>repeated string versionInfo = 1;</code>
			 */
			public java.util.List<java.lang.String> getVersionInfoList() {
				return java.util.Collections.unmodifiableList(versionInfo_);
			}

			/**
			 * <code>repeated string versionInfo = 1;</code>
			 */
			public int getVersionInfoCount() {
				return versionInfo_.size();
			}

			/**
			 * <code>repeated string versionInfo = 1;</code>
			 */
			public java.lang.String getVersionInfo(
					int index ) {
				return versionInfo_.get(index);
			}

			/**
			 * <code>repeated string versionInfo = 1;</code>
			 */
			public com.google.protobuf.ByteString getVersionInfoBytes(
					int index ) {
				return versionInfo_.getByteString(index);
			}

			/**
			 * <code>repeated string versionInfo = 1;</code>
			 */
			public Builder setVersionInfo(
					int index,
					java.lang.String value ) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureVersionInfoIsMutable();
				versionInfo_.set(
						index,
						value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string versionInfo = 1;</code>
			 */
			public Builder addVersionInfo(
					java.lang.String value ) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureVersionInfoIsMutable();
				versionInfo_.add(value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string versionInfo = 1;</code>
			 */
			public Builder addAllVersionInfo(
					java.lang.Iterable<java.lang.String> values ) {
				ensureVersionInfoIsMutable();
				super.addAll(
						values,
						versionInfo_);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string versionInfo = 1;</code>
			 */
			public Builder clearVersionInfo() {
				versionInfo_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000001);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string versionInfo = 1;</code>
			 */
			public Builder addVersionInfoBytes(
					com.google.protobuf.ByteString value ) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureVersionInfoIsMutable();
				versionInfo_.add(value);
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:VersionResponse)
		}

		static {
			defaultInstance = new VersionResponse(
					true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:VersionResponse)
	}

	/**
	 * Protobuf service {@code VersionService}
	 */
	public static abstract class VersionService implements
			com.google.protobuf.Service
	{
		protected VersionService() {}

		public interface Interface
		{
			/**
			 * <code>rpc version(.VersionRequest) returns (.VersionResponse);</code>
			 */
			public abstract void version(
					com.google.protobuf.RpcController controller,
					mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest request,
					com.google.protobuf.RpcCallback<mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse> done );

		}

		public static com.google.protobuf.Service newReflectiveService(
				final Interface impl ) {
			return new VersionService() {
				@java.lang.Override
				public void version(
						com.google.protobuf.RpcController controller,
						mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest request,
						com.google.protobuf.RpcCallback<mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse> done ) {
					impl.version(
							controller,
							request,
							done);
				}

			};
		}

		public static com.google.protobuf.BlockingService newReflectiveBlockingService(
				final BlockingInterface impl ) {
			return new com.google.protobuf.BlockingService() {
				public final com.google.protobuf.Descriptors.ServiceDescriptor getDescriptorForType() {
					return getDescriptor();
				}

				public final com.google.protobuf.Message callBlockingMethod(
						com.google.protobuf.Descriptors.MethodDescriptor method,
						com.google.protobuf.RpcController controller,
						com.google.protobuf.Message request )
						throws com.google.protobuf.ServiceException {
					if (method.getService() != getDescriptor()) {
						throw new java.lang.IllegalArgumentException(
								"Service.callBlockingMethod() given method descriptor for " + "wrong service type.");
					}
					switch (method.getIndex()) {
						case 0:
							return impl
									.version(
											controller,
											(mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest) request);
						default:
							throw new java.lang.AssertionError(
									"Can't get here.");
					}
				}

				public final com.google.protobuf.Message getRequestPrototype(
						com.google.protobuf.Descriptors.MethodDescriptor method ) {
					if (method.getService() != getDescriptor()) {
						throw new java.lang.IllegalArgumentException(
								"Service.getRequestPrototype() given method " + "descriptor for wrong service type.");
					}
					switch (method.getIndex()) {
						case 0:
							return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest
									.getDefaultInstance();
						default:
							throw new java.lang.AssertionError(
									"Can't get here.");
					}
				}

				public final com.google.protobuf.Message getResponsePrototype(
						com.google.protobuf.Descriptors.MethodDescriptor method ) {
					if (method.getService() != getDescriptor()) {
						throw new java.lang.IllegalArgumentException(
								"Service.getResponsePrototype() given method " + "descriptor for wrong service type.");
					}
					switch (method.getIndex()) {
						case 0:
							return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse
									.getDefaultInstance();
						default:
							throw new java.lang.AssertionError(
									"Can't get here.");
					}
				}

			};
		}

		/**
		 * <code>rpc version(.VersionRequest) returns (.VersionResponse);</code>
		 */
		public abstract void version(
				com.google.protobuf.RpcController controller,
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest request,
				com.google.protobuf.RpcCallback<mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse> done );

		public static final com.google.protobuf.Descriptors.ServiceDescriptor getDescriptor() {
			return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos
					.getDescriptor()
					.getServices()
					.get(
							0);
		}

		public final com.google.protobuf.Descriptors.ServiceDescriptor getDescriptorForType() {
			return getDescriptor();
		}

		public final void callMethod(
				com.google.protobuf.Descriptors.MethodDescriptor method,
				com.google.protobuf.RpcController controller,
				com.google.protobuf.Message request,
				com.google.protobuf.RpcCallback<com.google.protobuf.Message> done ) {
			if (method.getService() != getDescriptor()) {
				throw new java.lang.IllegalArgumentException(
						"Service.callMethod() given method descriptor for wrong " + "service type.");
			}
			switch (method.getIndex()) {
				case 0:
					this
							.version(
									controller,
									(mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest) request,
									com.google.protobuf.RpcUtil
											.<mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse> specializeCallback(done));
					return;
				default:
					throw new java.lang.AssertionError(
							"Can't get here.");
			}
		}

		public final com.google.protobuf.Message getRequestPrototype(
				com.google.protobuf.Descriptors.MethodDescriptor method ) {
			if (method.getService() != getDescriptor()) {
				throw new java.lang.IllegalArgumentException(
						"Service.getRequestPrototype() given method " + "descriptor for wrong service type.");
			}
			switch (method.getIndex()) {
				case 0:
					return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest
							.getDefaultInstance();
				default:
					throw new java.lang.AssertionError(
							"Can't get here.");
			}
		}

		public final com.google.protobuf.Message getResponsePrototype(
				com.google.protobuf.Descriptors.MethodDescriptor method ) {
			if (method.getService() != getDescriptor()) {
				throw new java.lang.IllegalArgumentException(
						"Service.getResponsePrototype() given method " + "descriptor for wrong service type.");
			}
			switch (method.getIndex()) {
				case 0:
					return mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse
							.getDefaultInstance();
				default:
					throw new java.lang.AssertionError(
							"Can't get here.");
			}
		}

		public static Stub newStub(
				com.google.protobuf.RpcChannel channel ) {
			return new Stub(
					channel);
		}

		public static final class Stub extends
				mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionService implements
				Interface
		{
			private Stub(
					com.google.protobuf.RpcChannel channel ) {
				this.channel = channel;
			}

			private final com.google.protobuf.RpcChannel channel;

			public com.google.protobuf.RpcChannel getChannel() {
				return channel;
			}

			public void version(
					com.google.protobuf.RpcController controller,
					mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest request,
					com.google.protobuf.RpcCallback<mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse> done ) {
				channel
						.callMethod(
								getDescriptor().getMethods().get(
										0),
								controller,
								request,
								mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse
										.getDefaultInstance(),
								com.google.protobuf.RpcUtil
										.generalizeCallback(
												done,
												mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse.class,
												mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse
														.getDefaultInstance()));
			}
		}

		public static BlockingInterface newBlockingStub(
				com.google.protobuf.BlockingRpcChannel channel ) {
			return new BlockingStub(
					channel);
		}

		public interface BlockingInterface
		{
			public mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse version(
					com.google.protobuf.RpcController controller,
					mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest request )
					throws com.google.protobuf.ServiceException;
		}

		private static final class BlockingStub implements
				BlockingInterface
		{
			private BlockingStub(
					com.google.protobuf.BlockingRpcChannel channel ) {
				this.channel = channel;
			}

			private final com.google.protobuf.BlockingRpcChannel channel;

			public mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse version(
					com.google.protobuf.RpcController controller,
					mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionRequest request )
					throws com.google.protobuf.ServiceException {
				return (mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse) channel
						.callBlockingMethod(
								getDescriptor().getMethods().get(
										0),
								controller,
								request,
								mil.nga.giat.geowave.datastore.hbase.coprocessors.protobuf.VersionProtos.VersionResponse
										.getDefaultInstance());
			}

		}

		// @@protoc_insertion_point(class_scope:VersionService)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_VersionRequest_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_VersionRequest_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_VersionResponse_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_VersionResponse_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = {
			"\n\rVersion.proto\"\020\n\016VersionRequest\"&\n\017Ver"
					+ "sionResponse\022\023\n\013versionInfo\030\001 \003(\t2>\n\016Ver"
					+ "sionService\022,\n\007version\022\017.VersionRequest\032"
					+ "\020.VersionResponseBL\n3mil.nga.giat.geowav" + "e.datastore.hbase.query.protobufB\rVersio"
					+ "nProtosH\001\210\001\001\240\001\001"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root ) {
				descriptor = root;
				internal_static_VersionRequest_descriptor = getDescriptor().getMessageTypes().get(
						0);
				internal_static_VersionRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_VersionRequest_descriptor,
						new java.lang.String[] {});
				internal_static_VersionResponse_descriptor = getDescriptor().getMessageTypes().get(
						1);
				internal_static_VersionResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_VersionResponse_descriptor,
						new java.lang.String[] {
							"VersionInfo",
						});
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
				descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {},
				assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
