// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeoWaveVectorQuery.proto

package mil.nga.giat.geowave.service.grpc.protobuf;

public interface BaseGeoWaveQueryParamtersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BaseGeoWaveQueryParamters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string storeName = 1;</code>
   */
  java.lang.String getStoreName();
  /**
   * <code>optional string storeName = 1;</code>
   */
  com.google.protobuf.ByteString
      getStoreNameBytes();

  /**
   * <code>optional bytes indexId = 2;</code>
   */
  com.google.protobuf.ByteString getIndexId();

  /**
   * <code>optional bytes adapterId = 3;</code>
   */
  com.google.protobuf.ByteString getAdapterId();
}
