// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeoWaveVectorQuery.proto

package mil.nga.giat.geowave.service.grpc.protobuf;

/**
 * <pre>
 *decimal degree coordinate type
 * </pre>
 *
 * Protobuf type {@code Coordinate}
 */
public  final class Coordinate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Coordinate)
    CoordinateOrBuilder {
  // Use Coordinate.newBuilder() to construct.
  private Coordinate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Coordinate() {
    lat_ = 0D;
    lon_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Coordinate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 9: {

            lat_ = input.readDouble();
            break;
          }
          case 17: {

            lon_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mil.nga.giat.geowave.service.grpc.protobuf.VectorQueryService.internal_static_Coordinate_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mil.nga.giat.geowave.service.grpc.protobuf.VectorQueryService.internal_static_Coordinate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mil.nga.giat.geowave.service.grpc.protobuf.Coordinate.class, mil.nga.giat.geowave.service.grpc.protobuf.Coordinate.Builder.class);
  }

  public static final int LAT_FIELD_NUMBER = 1;
  private double lat_;
  /**
   * <code>optional double lat = 1;</code>
   */
  public double getLat() {
    return lat_;
  }

  public static final int LON_FIELD_NUMBER = 2;
  private double lon_;
  /**
   * <code>optional double lon = 2;</code>
   */
  public double getLon() {
    return lon_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lat_ != 0D) {
      output.writeDouble(1, lat_);
    }
    if (lon_ != 0D) {
      output.writeDouble(2, lon_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lat_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, lat_);
    }
    if (lon_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, lon_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof mil.nga.giat.geowave.service.grpc.protobuf.Coordinate)) {
      return super.equals(obj);
    }
    mil.nga.giat.geowave.service.grpc.protobuf.Coordinate other = (mil.nga.giat.geowave.service.grpc.protobuf.Coordinate) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getLat())
        == java.lang.Double.doubleToLongBits(
            other.getLat()));
    result = result && (
        java.lang.Double.doubleToLongBits(getLon())
        == java.lang.Double.doubleToLongBits(
            other.getLon()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + LAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLat()));
    hash = (37 * hash) + LON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLon()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static mil.nga.giat.geowave.service.grpc.protobuf.Coordinate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mil.nga.giat.geowave.service.grpc.protobuf.Coordinate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mil.nga.giat.geowave.service.grpc.protobuf.Coordinate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mil.nga.giat.geowave.service.grpc.protobuf.Coordinate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mil.nga.giat.geowave.service.grpc.protobuf.Coordinate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mil.nga.giat.geowave.service.grpc.protobuf.Coordinate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mil.nga.giat.geowave.service.grpc.protobuf.Coordinate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mil.nga.giat.geowave.service.grpc.protobuf.Coordinate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mil.nga.giat.geowave.service.grpc.protobuf.Coordinate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mil.nga.giat.geowave.service.grpc.protobuf.Coordinate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mil.nga.giat.geowave.service.grpc.protobuf.Coordinate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *decimal degree coordinate type
   * </pre>
   *
   * Protobuf type {@code Coordinate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Coordinate)
      mil.nga.giat.geowave.service.grpc.protobuf.CoordinateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mil.nga.giat.geowave.service.grpc.protobuf.VectorQueryService.internal_static_Coordinate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mil.nga.giat.geowave.service.grpc.protobuf.VectorQueryService.internal_static_Coordinate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mil.nga.giat.geowave.service.grpc.protobuf.Coordinate.class, mil.nga.giat.geowave.service.grpc.protobuf.Coordinate.Builder.class);
    }

    // Construct using mil.nga.giat.geowave.service.grpc.protobuf.Coordinate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      lat_ = 0D;

      lon_ = 0D;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mil.nga.giat.geowave.service.grpc.protobuf.VectorQueryService.internal_static_Coordinate_descriptor;
    }

    public mil.nga.giat.geowave.service.grpc.protobuf.Coordinate getDefaultInstanceForType() {
      return mil.nga.giat.geowave.service.grpc.protobuf.Coordinate.getDefaultInstance();
    }

    public mil.nga.giat.geowave.service.grpc.protobuf.Coordinate build() {
      mil.nga.giat.geowave.service.grpc.protobuf.Coordinate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public mil.nga.giat.geowave.service.grpc.protobuf.Coordinate buildPartial() {
      mil.nga.giat.geowave.service.grpc.protobuf.Coordinate result = new mil.nga.giat.geowave.service.grpc.protobuf.Coordinate(this);
      result.lat_ = lat_;
      result.lon_ = lon_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof mil.nga.giat.geowave.service.grpc.protobuf.Coordinate) {
        return mergeFrom((mil.nga.giat.geowave.service.grpc.protobuf.Coordinate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(mil.nga.giat.geowave.service.grpc.protobuf.Coordinate other) {
      if (other == mil.nga.giat.geowave.service.grpc.protobuf.Coordinate.getDefaultInstance()) return this;
      if (other.getLat() != 0D) {
        setLat(other.getLat());
      }
      if (other.getLon() != 0D) {
        setLon(other.getLon());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      mil.nga.giat.geowave.service.grpc.protobuf.Coordinate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (mil.nga.giat.geowave.service.grpc.protobuf.Coordinate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double lat_ ;
    /**
     * <code>optional double lat = 1;</code>
     */
    public double getLat() {
      return lat_;
    }
    /**
     * <code>optional double lat = 1;</code>
     */
    public Builder setLat(double value) {
      
      lat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double lat = 1;</code>
     */
    public Builder clearLat() {
      
      lat_ = 0D;
      onChanged();
      return this;
    }

    private double lon_ ;
    /**
     * <code>optional double lon = 2;</code>
     */
    public double getLon() {
      return lon_;
    }
    /**
     * <code>optional double lon = 2;</code>
     */
    public Builder setLon(double value) {
      
      lon_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double lon = 2;</code>
     */
    public Builder clearLon() {
      
      lon_ = 0D;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Coordinate)
  }

  // @@protoc_insertion_point(class_scope:Coordinate)
  private static final mil.nga.giat.geowave.service.grpc.protobuf.Coordinate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mil.nga.giat.geowave.service.grpc.protobuf.Coordinate();
  }

  public static mil.nga.giat.geowave.service.grpc.protobuf.Coordinate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Coordinate>
      PARSER = new com.google.protobuf.AbstractParser<Coordinate>() {
    public Coordinate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Coordinate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Coordinate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Coordinate> getParserForType() {
    return PARSER;
  }

  public mil.nga.giat.geowave.service.grpc.protobuf.Coordinate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

