// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeoWaveVectorQuery.proto

package mil.nga.giat.geowave.service.grpc.protobuf;

public interface CoordinateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Coordinate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double lat = 1;</code>
   */
  double getLat();

  /**
   * <code>optional double lon = 2;</code>
   */
  double getLon();
}
