// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeoWaveVectorQuery.proto

package mil.nga.giat.geowave.service.grpc.protobuf;

public interface CQLQueryParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CQLQueryParameters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
   */
  boolean hasBaseParams();
  /**
   * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
   */
  mil.nga.giat.geowave.service.grpc.protobuf.BaseGeoWaveQueryParamters getBaseParams();
  /**
   * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
   */
  mil.nga.giat.geowave.service.grpc.protobuf.BaseGeoWaveQueryParamtersOrBuilder getBaseParamsOrBuilder();

  /**
   * <code>optional string cql = 2;</code>
   */
  java.lang.String getCql();
  /**
   * <code>optional string cql = 2;</code>
   */
  com.google.protobuf.ByteString
      getCqlBytes();
}
