// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeoWaveVectorQuery.proto

package mil.nga.giat.geowave.service.grpc.protobuf;

public interface SpatialQueryParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SpatialQueryParameters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
   */
  boolean hasBaseParams();
  /**
   * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
   */
  mil.nga.giat.geowave.service.grpc.protobuf.BaseGeoWaveQueryParamters getBaseParams();
  /**
   * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
   */
  mil.nga.giat.geowave.service.grpc.protobuf.BaseGeoWaveQueryParamtersOrBuilder getBaseParamsOrBuilder();

  /**
   * <pre>
   *ISO 19107 Geometry text definition
   * </pre>
   *
   * <code>optional string geometry = 2;</code>
   */
  java.lang.String getGeometry();
  /**
   * <pre>
   *ISO 19107 Geometry text definition
   * </pre>
   *
   * <code>optional string geometry = 2;</code>
   */
  com.google.protobuf.ByteString
      getGeometryBytes();

  /**
   * <code>repeated .Coordinate coordinates = 3;</code>
   */
  java.util.List<mil.nga.giat.geowave.service.grpc.protobuf.Coordinate> 
      getCoordinatesList();
  /**
   * <code>repeated .Coordinate coordinates = 3;</code>
   */
  mil.nga.giat.geowave.service.grpc.protobuf.Coordinate getCoordinates(int index);
  /**
   * <code>repeated .Coordinate coordinates = 3;</code>
   */
  int getCoordinatesCount();
  /**
   * <code>repeated .Coordinate coordinates = 3;</code>
   */
  java.util.List<? extends mil.nga.giat.geowave.service.grpc.protobuf.CoordinateOrBuilder> 
      getCoordinatesOrBuilderList();
  /**
   * <code>repeated .Coordinate coordinates = 3;</code>
   */
  mil.nga.giat.geowave.service.grpc.protobuf.CoordinateOrBuilder getCoordinatesOrBuilder(
      int index);
}
