// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeoWaveVectorQuery.proto

package mil.nga.giat.geowave.service.grpc.protobuf;

public final class VectorQueryService {
  private VectorQueryService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseGeoWaveQueryParamters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseGeoWaveQueryParamters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Coordinate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Coordinate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CQLQueryParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CQLQueryParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpatialQueryParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpatialQueryParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Feature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Feature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Feature_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Feature_AttributesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030GeoWaveVectorQuery.proto\"R\n\031BaseGeoWav" +
      "eQueryParamters\022\021\n\tstoreName\030\001 \001(\t\022\017\n\007in" +
      "dexId\030\002 \001(\014\022\021\n\tadapterId\030\003 \001(\014\"&\n\nCoordi" +
      "nate\022\013\n\003lat\030\001 \001(\001\022\013\n\003lon\030\002 \001(\001\"Q\n\022CQLQue" +
      "ryParameters\022.\n\nbaseParams\030\001 \001(\0132\032.BaseG" +
      "eoWaveQueryParamters\022\013\n\003cql\030\002 \001(\t\"|\n\026Spa" +
      "tialQueryParameters\022.\n\nbaseParams\030\001 \001(\0132" +
      "\032.BaseGeoWaveQueryParamters\022\020\n\010geometry\030" +
      "\002 \001(\t\022 \n\013coordinates\030\003 \003(\0132\013.Coordinate\"" +
      "j\n\007Feature\022,\n\nattributes\030\001 \003(\0132\030.Feature",
      ".AttributesEntry\0321\n\017AttributesEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012s\n\013VectorQue" +
      "ry\022-\n\010CqlQuery\022\023.CQLQueryParameters\032\010.Fe" +
      "ature\"\0000\001\0225\n\014SpatialQuery\022\027.SpatialQuery" +
      "Parameters\032\010.Feature\"\0000\001BB\n*mil.nga.giat" +
      ".geowave.service.grpc.protobufB\022VectorQu" +
      "eryServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BaseGeoWaveQueryParamters_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseGeoWaveQueryParamters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseGeoWaveQueryParamters_descriptor,
        new java.lang.String[] { "StoreName", "IndexId", "AdapterId", });
    internal_static_Coordinate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Coordinate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Coordinate_descriptor,
        new java.lang.String[] { "Lat", "Lon", });
    internal_static_CQLQueryParameters_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CQLQueryParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CQLQueryParameters_descriptor,
        new java.lang.String[] { "BaseParams", "Cql", });
    internal_static_SpatialQueryParameters_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SpatialQueryParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpatialQueryParameters_descriptor,
        new java.lang.String[] { "BaseParams", "Geometry", "Coordinates", });
    internal_static_Feature_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Feature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Feature_descriptor,
        new java.lang.String[] { "Attributes", });
    internal_static_Feature_AttributesEntry_descriptor =
      internal_static_Feature_descriptor.getNestedTypes().get(0);
    internal_static_Feature_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Feature_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
