// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdapterVectorQuery.proto

package mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf;

public final class AdapterVectorQueryService
{
	private AdapterVectorQueryService() {}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry ) {}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry ) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	static final com.google.protobuf.Descriptors.Descriptor internal_static_BaseGeoWaveQueryParamters_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_BaseGeoWaveQueryParamters_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_CQLQueryParameters_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_CQLQueryParameters_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_Feature_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Feature_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_Feature_AttributesEntry_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Feature_AttributesEntry_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = {
			"\n\030AdapterVectorQuery.proto\"R\n\031BaseGeoWav"
					+ "eQueryParamters\022\021\n\tstoreName\030\001 \001(\t\022\017\n\007in"
					+ "dexId\030\002 \001(\t\022\021\n\tadapterId\030\003 \001(\t\"Q\n\022CQLQue"
					+ "ryParameters\022.\n\nbaseParams\030\001 \001(\0132\032.BaseG"
					+ "eoWaveQueryParamters\022\013\n\003cql\030\002 \001(\t\"j\n\007Fea"
					+ "ture\022,\n\nattributes\030\001 \003(\0132\030.Feature.Attri"
					+ "butesEntry\0321\n\017AttributesEntry\022\013\n\003key\030\001 \001"
					+ "(\t\022\r\n\005value\030\002 \001(\t:\0028\0012C\n\022AdapterVectorQu"
					+ "ery\022-\n\010CqlQuery\022\023.CQLQueryParameters\032\010.F"
					+ "eature\"\0000\001BV\n7mil.nga.giat.geowave.grpc.",
			"adapter.vector.query.protobufB\031AdapterVe" + "ctorQueryServiceP\001b\006proto3"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root ) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
				descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {},
				assigner);
		internal_static_BaseGeoWaveQueryParamters_descriptor = getDescriptor().getMessageTypes().get(
				0);
		internal_static_BaseGeoWaveQueryParamters_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_BaseGeoWaveQueryParamters_descriptor,
				new java.lang.String[] {
					"StoreName",
					"IndexId",
					"AdapterId",
				});
		internal_static_CQLQueryParameters_descriptor = getDescriptor().getMessageTypes().get(
				1);
		internal_static_CQLQueryParameters_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_CQLQueryParameters_descriptor,
				new java.lang.String[] {
					"BaseParams",
					"Cql",
				});
		internal_static_Feature_descriptor = getDescriptor().getMessageTypes().get(
				2);
		internal_static_Feature_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_Feature_descriptor,
				new java.lang.String[] {
					"Attributes",
				});
		internal_static_Feature_AttributesEntry_descriptor = internal_static_Feature_descriptor.getNestedTypes().get(
				0);
		internal_static_Feature_AttributesEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_Feature_AttributesEntry_descriptor,
				new java.lang.String[] {
					"Key",
					"Value",
				});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
