// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdapterVectorQuery.proto

package mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf;

public interface BaseGeoWaveQueryParamtersOrBuilder extends
		// @@protoc_insertion_point(interface_extends:BaseGeoWaveQueryParamters)
		com.google.protobuf.MessageOrBuilder
{

	/**
	 * <code>optional string storeName = 1;</code>
	 */
	java.lang.String getStoreName();

	/**
	 * <code>optional string storeName = 1;</code>
	 */
	com.google.protobuf.ByteString getStoreNameBytes();

	/**
	 * <code>optional string indexId = 2;</code>
	 */
	java.lang.String getIndexId();

	/**
	 * <code>optional string indexId = 2;</code>
	 */
	com.google.protobuf.ByteString getIndexIdBytes();

	/**
	 * <code>optional string adapterId = 3;</code>
	 */
	java.lang.String getAdapterId();

	/**
	 * <code>optional string adapterId = 3;</code>
	 */
	com.google.protobuf.ByteString getAdapterIdBytes();
}
