// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdapterVectorQuery.proto

package mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf;

/**
 * <pre>
 * Base query parameters as defined by AbstractGeoWaveQuery.java
 * </pre>
 *
 * Protobuf type {@code BaseGeoWaveQueryParamters}
 */
public final class BaseGeoWaveQueryParamters extends
		com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:BaseGeoWaveQueryParamters)
		BaseGeoWaveQueryParamtersOrBuilder
{
	// Use BaseGeoWaveQueryParamters.newBuilder() to construct.
	private BaseGeoWaveQueryParamters(
			com.google.protobuf.GeneratedMessageV3.Builder<?> builder ) {
		super(
				builder);
	}

	private BaseGeoWaveQueryParamters() {
		storeName_ = "";
		indexId_ = "";
		adapterId_ = "";
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
	}

	private BaseGeoWaveQueryParamters(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
		this();
		int mutable_bitField0_ = 0;
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						java.lang.String s = input.readStringRequireUtf8();

						storeName_ = s;
						break;
					}
					case 18: {
						java.lang.String s = input.readStringRequireUtf8();

						indexId_ = s;
						break;
					}
					case 26: {
						java.lang.String s = input.readStringRequireUtf8();

						adapterId_ = s;
						break;
					}
				}
			}
		}
		catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.setUnfinishedMessage(this);
		}
		catch (java.io.IOException e) {
			throw new com.google.protobuf.InvalidProtocolBufferException(
					e).setUnfinishedMessage(this);
		}
		finally {
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_BaseGeoWaveQueryParamters_descriptor;
	}

	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_BaseGeoWaveQueryParamters_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
						mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters.class,
						mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters.Builder.class);
	}

	public static final int STORENAME_FIELD_NUMBER = 1;
	private volatile java.lang.Object storeName_;

	/**
	 * <code>optional string storeName = 1;</code>
	 */
	public java.lang.String getStoreName() {
		java.lang.Object ref = storeName_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		}
		else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			storeName_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string storeName = 1;</code>
	 */
	public com.google.protobuf.ByteString getStoreNameBytes() {
		java.lang.Object ref = storeName_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			storeName_ = b;
			return b;
		}
		else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int INDEXID_FIELD_NUMBER = 2;
	private volatile java.lang.Object indexId_;

	/**
	 * <code>optional string indexId = 2;</code>
	 */
	public java.lang.String getIndexId() {
		java.lang.Object ref = indexId_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		}
		else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			indexId_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string indexId = 2;</code>
	 */
	public com.google.protobuf.ByteString getIndexIdBytes() {
		java.lang.Object ref = indexId_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			indexId_ = b;
			return b;
		}
		else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int ADAPTERID_FIELD_NUMBER = 3;
	private volatile java.lang.Object adapterId_;

	/**
	 * <code>optional string adapterId = 3;</code>
	 */
	public java.lang.String getAdapterId() {
		java.lang.Object ref = adapterId_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		}
		else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			adapterId_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string adapterId = 3;</code>
	 */
	public com.google.protobuf.ByteString getAdapterIdBytes() {
		java.lang.Object ref = adapterId_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			adapterId_ = b;
			return b;
		}
		else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	private byte memoizedIsInitialized = -1;

	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1) return true;
		if (isInitialized == 0) return false;

		memoizedIsInitialized = 1;
		return true;
	}

	public void writeTo(
			com.google.protobuf.CodedOutputStream output )
			throws java.io.IOException {
		if (!getStoreNameBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessageV3.writeString(
					output,
					1,
					storeName_);
		}
		if (!getIndexIdBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessageV3.writeString(
					output,
					2,
					indexId_);
		}
		if (!getAdapterIdBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessageV3.writeString(
					output,
					3,
					adapterId_);
		}
	}

	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1) return size;

		size = 0;
		if (!getStoreNameBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(
					1,
					storeName_);
		}
		if (!getIndexIdBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(
					2,
					indexId_);
		}
		if (!getAdapterIdBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(
					3,
					adapterId_);
		}
		memoizedSize = size;
		return size;
	}

	private static final long serialVersionUID = 0L;

	@java.lang.Override
	public boolean equals(
			final java.lang.Object obj ) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters)) {
			return super.equals(obj);
		}
		mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters other = (mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters) obj;

		boolean result = true;
		result = result && getStoreName().equals(
				other.getStoreName());
		result = result && getIndexId().equals(
				other.getIndexId());
		result = result && getAdapterId().equals(
				other.getAdapterId());
		return result;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptorForType().hashCode();
		hash = (37 * hash) + STORENAME_FIELD_NUMBER;
		hash = (53 * hash) + getStoreName().hashCode();
		hash = (37 * hash) + INDEXID_FIELD_NUMBER;
		hash = (53 * hash) + getIndexId().hashCode();
		hash = (37 * hash) + ADAPTERID_FIELD_NUMBER;
		hash = (53 * hash) + getAdapterId().hashCode();
		hash = (29 * hash) + unknownFields.hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters parseFrom(
			com.google.protobuf.ByteString data )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(
				data,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters parseFrom(
			byte[] data )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters parseFrom(
			byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(
				data,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters parseFrom(
			java.io.InputStream input )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters parseFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters parseDelimitedFrom(
			java.io.InputStream input )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
				PARSER,
				input);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters parseDelimitedFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
				PARSER,
				input,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters parseFrom(
			com.google.protobuf.CodedInputStream input )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input,
				extensionRegistry);
	}

	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters prototype ) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(
				prototype);
	}

	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(
			com.google.protobuf.GeneratedMessageV3.BuilderParent parent ) {
		Builder builder = new Builder(
				parent);
		return builder;
	}

	/**
	 * <pre>
	 * Base query parameters as defined by AbstractGeoWaveQuery.java
	 * </pre>
	 *
	 * Protobuf type {@code BaseGeoWaveQueryParamters}
	 */
	public static final class Builder extends
			com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:BaseGeoWaveQueryParamters)
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamtersOrBuilder
	{
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_BaseGeoWaveQueryParamters_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_BaseGeoWaveQueryParamters_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters.class,
							mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters.Builder.class);
		}

		// Construct using
		// mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent ) {
			super(
					parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
		}

		public Builder clear() {
			super.clear();
			storeName_ = "";

			indexId_ = "";

			adapterId_ = "";

			return this;
		}

		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_BaseGeoWaveQueryParamters_descriptor;
		}

		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters getDefaultInstanceForType() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters
					.getDefaultInstance();
		}

		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters build() {
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters buildPartial() {
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters result = new mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters(
					this);
			result.storeName_ = storeName_;
			result.indexId_ = indexId_;
			result.adapterId_ = adapterId_;
			onBuilt();
			return result;
		}

		public Builder clone() {
			return (Builder) super.clone();
		}

		public Builder setField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				Object value ) {
			return (Builder) super.setField(
					field,
					value);
		}

		public Builder clearField(
				com.google.protobuf.Descriptors.FieldDescriptor field ) {
			return (Builder) super.clearField(field);
		}

		public Builder clearOneof(
				com.google.protobuf.Descriptors.OneofDescriptor oneof ) {
			return (Builder) super.clearOneof(oneof);
		}

		public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index,
				Object value ) {
			return (Builder) super.setRepeatedField(
					field,
					index,
					value);
		}

		public Builder addRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				Object value ) {
			return (Builder) super.addRepeatedField(
					field,
					value);
		}

		public Builder mergeFrom(
				com.google.protobuf.Message other ) {
			if (other instanceof mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters) {
				return mergeFrom((mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters) other);
			}
			else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(
				mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters other ) {
			if (other == mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters
					.getDefaultInstance()) return this;
			if (!other.getStoreName().isEmpty()) {
				storeName_ = other.storeName_;
				onChanged();
			}
			if (!other.getIndexId().isEmpty()) {
				indexId_ = other.indexId_;
				onChanged();
			}
			if (!other.getAdapterId().isEmpty()) {
				adapterId_ = other.adapterId_;
				onChanged();
			}
			onChanged();
			return this;
		}

		public final boolean isInitialized() {
			return true;
		}

		public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(
						input,
						extensionRegistry);
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters) e
						.getUnfinishedMessage();
				throw e.unwrapIOException();
			}
			finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private java.lang.Object storeName_ = "";

		/**
		 * <code>optional string storeName = 1;</code>
		 */
		public java.lang.String getStoreName() {
			java.lang.Object ref = storeName_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				storeName_ = s;
				return s;
			}
			else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string storeName = 1;</code>
		 */
		public com.google.protobuf.ByteString getStoreNameBytes() {
			java.lang.Object ref = storeName_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				storeName_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string storeName = 1;</code>
		 */
		public Builder setStoreName(
				java.lang.String value ) {
			if (value == null) {
				throw new NullPointerException();
			}

			storeName_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string storeName = 1;</code>
		 */
		public Builder clearStoreName() {

			storeName_ = getDefaultInstance().getStoreName();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string storeName = 1;</code>
		 */
		public Builder setStoreNameBytes(
				com.google.protobuf.ByteString value ) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			storeName_ = value;
			onChanged();
			return this;
		}

		private java.lang.Object indexId_ = "";

		/**
		 * <code>optional string indexId = 2;</code>
		 */
		public java.lang.String getIndexId() {
			java.lang.Object ref = indexId_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				indexId_ = s;
				return s;
			}
			else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string indexId = 2;</code>
		 */
		public com.google.protobuf.ByteString getIndexIdBytes() {
			java.lang.Object ref = indexId_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				indexId_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string indexId = 2;</code>
		 */
		public Builder setIndexId(
				java.lang.String value ) {
			if (value == null) {
				throw new NullPointerException();
			}

			indexId_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string indexId = 2;</code>
		 */
		public Builder clearIndexId() {

			indexId_ = getDefaultInstance().getIndexId();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string indexId = 2;</code>
		 */
		public Builder setIndexIdBytes(
				com.google.protobuf.ByteString value ) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			indexId_ = value;
			onChanged();
			return this;
		}

		private java.lang.Object adapterId_ = "";

		/**
		 * <code>optional string adapterId = 3;</code>
		 */
		public java.lang.String getAdapterId() {
			java.lang.Object ref = adapterId_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				adapterId_ = s;
				return s;
			}
			else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string adapterId = 3;</code>
		 */
		public com.google.protobuf.ByteString getAdapterIdBytes() {
			java.lang.Object ref = adapterId_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				adapterId_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string adapterId = 3;</code>
		 */
		public Builder setAdapterId(
				java.lang.String value ) {
			if (value == null) {
				throw new NullPointerException();
			}

			adapterId_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string adapterId = 3;</code>
		 */
		public Builder clearAdapterId() {

			adapterId_ = getDefaultInstance().getAdapterId();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string adapterId = 3;</code>
		 */
		public Builder setAdapterIdBytes(
				com.google.protobuf.ByteString value ) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			adapterId_ = value;
			onChanged();
			return this;
		}

		public final Builder setUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields ) {
			return this;
		}

		public final Builder mergeUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields ) {
			return this;
		}

		// @@protoc_insertion_point(builder_scope:BaseGeoWaveQueryParamters)
	}

	// @@protoc_insertion_point(class_scope:BaseGeoWaveQueryParamters)
	private static final mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters();
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<BaseGeoWaveQueryParamters> PARSER = new com.google.protobuf.AbstractParser<BaseGeoWaveQueryParamters>() {
		public BaseGeoWaveQueryParamters parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return new BaseGeoWaveQueryParamters(
					input,
					extensionRegistry);
		}
	};

	public static com.google.protobuf.Parser<BaseGeoWaveQueryParamters> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<BaseGeoWaveQueryParamters> getParserForType() {
		return PARSER;
	}

	public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
