// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdapterVectorQuery.proto

package mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf;

/**
 * <pre>
 * A CQL query string to be executed by the server
 * </pre>
 *
 * Protobuf type {@code CQLQueryParameters}
 */
public final class CQLQueryParameters extends
		com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:CQLQueryParameters)
		CQLQueryParametersOrBuilder
{
	// Use CQLQueryParameters.newBuilder() to construct.
	private CQLQueryParameters(
			com.google.protobuf.GeneratedMessageV3.Builder<?> builder ) {
		super(
				builder);
	}

	private CQLQueryParameters() {
		cql_ = "";
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
	}

	private CQLQueryParameters(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
		this();
		int mutable_bitField0_ = 0;
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters.Builder subBuilder = null;
						if (baseParams_ != null) {
							subBuilder = baseParams_.toBuilder();
						}
						baseParams_ = input.readMessage(
								mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters
										.parser(),
								extensionRegistry);
						if (subBuilder != null) {
							subBuilder.mergeFrom(baseParams_);
							baseParams_ = subBuilder.buildPartial();
						}

						break;
					}
					case 18: {
						java.lang.String s = input.readStringRequireUtf8();

						cql_ = s;
						break;
					}
				}
			}
		}
		catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.setUnfinishedMessage(this);
		}
		catch (java.io.IOException e) {
			throw new com.google.protobuf.InvalidProtocolBufferException(
					e).setUnfinishedMessage(this);
		}
		finally {
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_CQLQueryParameters_descriptor;
	}

	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_CQLQueryParameters_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
						mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters.class,
						mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters.Builder.class);
	}

	public static final int BASEPARAMS_FIELD_NUMBER = 1;
	private mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters baseParams_;

	/**
	 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
	 */
	public boolean hasBaseParams() {
		return baseParams_ != null;
	}

	/**
	 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
	 */
	public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters getBaseParams() {
		return baseParams_ == null ? mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters
				.getDefaultInstance() : baseParams_;
	}

	/**
	 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
	 */
	public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamtersOrBuilder getBaseParamsOrBuilder() {
		return getBaseParams();
	}

	public static final int CQL_FIELD_NUMBER = 2;
	private volatile java.lang.Object cql_;

	/**
	 * <code>optional string cql = 2;</code>
	 */
	public java.lang.String getCql() {
		java.lang.Object ref = cql_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		}
		else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			cql_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string cql = 2;</code>
	 */
	public com.google.protobuf.ByteString getCqlBytes() {
		java.lang.Object ref = cql_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			cql_ = b;
			return b;
		}
		else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	private byte memoizedIsInitialized = -1;

	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1) return true;
		if (isInitialized == 0) return false;

		memoizedIsInitialized = 1;
		return true;
	}

	public void writeTo(
			com.google.protobuf.CodedOutputStream output )
			throws java.io.IOException {
		if (baseParams_ != null) {
			output.writeMessage(
					1,
					getBaseParams());
		}
		if (!getCqlBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessageV3.writeString(
					output,
					2,
					cql_);
		}
	}

	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1) return size;

		size = 0;
		if (baseParams_ != null) {
			size += com.google.protobuf.CodedOutputStream.computeMessageSize(
					1,
					getBaseParams());
		}
		if (!getCqlBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(
					2,
					cql_);
		}
		memoizedSize = size;
		return size;
	}

	private static final long serialVersionUID = 0L;

	@java.lang.Override
	public boolean equals(
			final java.lang.Object obj ) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters)) {
			return super.equals(obj);
		}
		mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters other = (mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters) obj;

		boolean result = true;
		result = result && (hasBaseParams() == other.hasBaseParams());
		if (hasBaseParams()) {
			result = result && getBaseParams().equals(
					other.getBaseParams());
		}
		result = result && getCql().equals(
				other.getCql());
		return result;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptorForType().hashCode();
		if (hasBaseParams()) {
			hash = (37 * hash) + BASEPARAMS_FIELD_NUMBER;
			hash = (53 * hash) + getBaseParams().hashCode();
		}
		hash = (37 * hash) + CQL_FIELD_NUMBER;
		hash = (53 * hash) + getCql().hashCode();
		hash = (29 * hash) + unknownFields.hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters parseFrom(
			com.google.protobuf.ByteString data )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(
				data,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters parseFrom(
			byte[] data )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters parseFrom(
			byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(
				data,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters parseFrom(
			java.io.InputStream input )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters parseFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters parseDelimitedFrom(
			java.io.InputStream input )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
				PARSER,
				input);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters parseDelimitedFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
				PARSER,
				input,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters parseFrom(
			com.google.protobuf.CodedInputStream input )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input,
				extensionRegistry);
	}

	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters prototype ) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(
				prototype);
	}

	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(
			com.google.protobuf.GeneratedMessageV3.BuilderParent parent ) {
		Builder builder = new Builder(
				parent);
		return builder;
	}

	/**
	 * <pre>
	 * A CQL query string to be executed by the server
	 * </pre>
	 *
	 * Protobuf type {@code CQLQueryParameters}
	 */
	public static final class Builder extends
			com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:CQLQueryParameters)
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParametersOrBuilder
	{
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_CQLQueryParameters_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_CQLQueryParameters_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters.class,
							mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters.Builder.class);
		}

		// Construct using
		// mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent ) {
			super(
					parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
		}

		public Builder clear() {
			super.clear();
			if (baseParamsBuilder_ == null) {
				baseParams_ = null;
			}
			else {
				baseParams_ = null;
				baseParamsBuilder_ = null;
			}
			cql_ = "";

			return this;
		}

		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_CQLQueryParameters_descriptor;
		}

		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters getDefaultInstanceForType() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters.getDefaultInstance();
		}

		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters build() {
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters buildPartial() {
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters result = new mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters(
					this);
			if (baseParamsBuilder_ == null) {
				result.baseParams_ = baseParams_;
			}
			else {
				result.baseParams_ = baseParamsBuilder_.build();
			}
			result.cql_ = cql_;
			onBuilt();
			return result;
		}

		public Builder clone() {
			return (Builder) super.clone();
		}

		public Builder setField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				Object value ) {
			return (Builder) super.setField(
					field,
					value);
		}

		public Builder clearField(
				com.google.protobuf.Descriptors.FieldDescriptor field ) {
			return (Builder) super.clearField(field);
		}

		public Builder clearOneof(
				com.google.protobuf.Descriptors.OneofDescriptor oneof ) {
			return (Builder) super.clearOneof(oneof);
		}

		public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index,
				Object value ) {
			return (Builder) super.setRepeatedField(
					field,
					index,
					value);
		}

		public Builder addRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				Object value ) {
			return (Builder) super.addRepeatedField(
					field,
					value);
		}

		public Builder mergeFrom(
				com.google.protobuf.Message other ) {
			if (other instanceof mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters) {
				return mergeFrom((mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters) other);
			}
			else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(
				mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters other ) {
			if (other == mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters
					.getDefaultInstance()) return this;
			if (other.hasBaseParams()) {
				mergeBaseParams(other.getBaseParams());
			}
			if (!other.getCql().isEmpty()) {
				cql_ = other.cql_;
				onChanged();
			}
			onChanged();
			return this;
		}

		public final boolean isInitialized() {
			return true;
		}

		public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(
						input,
						extensionRegistry);
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters) e
						.getUnfinishedMessage();
				throw e.unwrapIOException();
			}
			finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters baseParams_ = null;
		private com.google.protobuf.SingleFieldBuilderV3<mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters, mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters.Builder, mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamtersOrBuilder> baseParamsBuilder_;

		/**
		 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
		 */
		public boolean hasBaseParams() {
			return baseParamsBuilder_ != null || baseParams_ != null;
		}

		/**
		 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
		 */
		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters getBaseParams() {
			if (baseParamsBuilder_ == null) {
				return baseParams_ == null ? mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters
						.getDefaultInstance() : baseParams_;
			}
			else {
				return baseParamsBuilder_.getMessage();
			}
		}

		/**
		 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
		 */
		public Builder setBaseParams(
				mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters value ) {
			if (baseParamsBuilder_ == null) {
				if (value == null) {
					throw new NullPointerException();
				}
				baseParams_ = value;
				onChanged();
			}
			else {
				baseParamsBuilder_.setMessage(value);
			}

			return this;
		}

		/**
		 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
		 */
		public Builder setBaseParams(
				mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters.Builder builderForValue ) {
			if (baseParamsBuilder_ == null) {
				baseParams_ = builderForValue.build();
				onChanged();
			}
			else {
				baseParamsBuilder_.setMessage(builderForValue.build());
			}

			return this;
		}

		/**
		 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
		 */
		public Builder mergeBaseParams(
				mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters value ) {
			if (baseParamsBuilder_ == null) {
				if (baseParams_ != null) {
					baseParams_ = mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters
							.newBuilder(
									baseParams_)
							.mergeFrom(
									value)
							.buildPartial();
				}
				else {
					baseParams_ = value;
				}
				onChanged();
			}
			else {
				baseParamsBuilder_.mergeFrom(value);
			}

			return this;
		}

		/**
		 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
		 */
		public Builder clearBaseParams() {
			if (baseParamsBuilder_ == null) {
				baseParams_ = null;
				onChanged();
			}
			else {
				baseParams_ = null;
				baseParamsBuilder_ = null;
			}

			return this;
		}

		/**
		 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
		 */
		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters.Builder getBaseParamsBuilder() {

			onChanged();
			return getBaseParamsFieldBuilder().getBuilder();
		}

		/**
		 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
		 */
		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamtersOrBuilder getBaseParamsOrBuilder() {
			if (baseParamsBuilder_ != null) {
				return baseParamsBuilder_.getMessageOrBuilder();
			}
			else {
				return baseParams_ == null ? mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters
						.getDefaultInstance() : baseParams_;
			}
		}

		/**
		 * <code>optional .BaseGeoWaveQueryParamters baseParams = 1;</code>
		 */
		private com.google.protobuf.SingleFieldBuilderV3<mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters, mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters.Builder, mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamtersOrBuilder> getBaseParamsFieldBuilder() {
			if (baseParamsBuilder_ == null) {
				baseParamsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters, mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamters.Builder, mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.BaseGeoWaveQueryParamtersOrBuilder>(
						getBaseParams(),
						getParentForChildren(),
						isClean());
				baseParams_ = null;
			}
			return baseParamsBuilder_;
		}

		private java.lang.Object cql_ = "";

		/**
		 * <code>optional string cql = 2;</code>
		 */
		public java.lang.String getCql() {
			java.lang.Object ref = cql_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				cql_ = s;
				return s;
			}
			else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string cql = 2;</code>
		 */
		public com.google.protobuf.ByteString getCqlBytes() {
			java.lang.Object ref = cql_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				cql_ = b;
				return b;
			}
			else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string cql = 2;</code>
		 */
		public Builder setCql(
				java.lang.String value ) {
			if (value == null) {
				throw new NullPointerException();
			}

			cql_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string cql = 2;</code>
		 */
		public Builder clearCql() {

			cql_ = getDefaultInstance().getCql();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string cql = 2;</code>
		 */
		public Builder setCqlBytes(
				com.google.protobuf.ByteString value ) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			cql_ = value;
			onChanged();
			return this;
		}

		public final Builder setUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields ) {
			return this;
		}

		public final Builder mergeUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields ) {
			return this;
		}

		// @@protoc_insertion_point(builder_scope:CQLQueryParameters)
	}

	// @@protoc_insertion_point(class_scope:CQLQueryParameters)
	private static final mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters();
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<CQLQueryParameters> PARSER = new com.google.protobuf.AbstractParser<CQLQueryParameters>() {
		public CQLQueryParameters parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return new CQLQueryParameters(
					input,
					extensionRegistry);
		}
	};

	public static com.google.protobuf.Parser<CQLQueryParameters> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<CQLQueryParameters> getParserForType() {
		return PARSER;
	}

	public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.CQLQueryParameters getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
