// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdapterVectorQuery.proto

package mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf;

/**
 * <pre>
 * a feature in this case is just a map of string key value pairs
 * </pre>
 *
 * Protobuf type {@code Feature}
 */
public final class Feature extends
		com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:Feature)
		FeatureOrBuilder
{
	// Use Feature.newBuilder() to construct.
	private Feature(
			com.google.protobuf.GeneratedMessageV3.Builder<?> builder ) {
		super(
				builder);
	}

	private Feature() {}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
	}

	private Feature(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
		this();
		int mutable_bitField0_ = 0;
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
							attributes_ = com.google.protobuf.MapField
									.newMapField(AttributesDefaultEntryHolder.defaultEntry);
							mutable_bitField0_ |= 0x00000001;
						}
						com.google.protobuf.MapEntry<java.lang.String, java.lang.String> attributes = input
								.readMessage(
										AttributesDefaultEntryHolder.defaultEntry.getParserForType(),
										extensionRegistry);
						attributes_.getMutableMap().put(
								attributes.getKey(),
								attributes.getValue());
						break;
					}
				}
			}
		}
		catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.setUnfinishedMessage(this);
		}
		catch (java.io.IOException e) {
			throw new com.google.protobuf.InvalidProtocolBufferException(
					e).setUnfinishedMessage(this);
		}
		finally {
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_Feature_descriptor;
	}

	@SuppressWarnings({
		"rawtypes"
	})
	protected com.google.protobuf.MapField internalGetMapField(
			int number ) {
		switch (number) {
			case 1:
				return internalGetAttributes();
			default:
				throw new RuntimeException(
						"Invalid map field number: " + number);
		}
	}

	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_Feature_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
						mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature.class,
						mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature.Builder.class);
	}

	public static final int ATTRIBUTES_FIELD_NUMBER = 1;

	private static final class AttributesDefaultEntryHolder
	{
		static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry = com.google.protobuf.MapEntry
				.<java.lang.String, java.lang.String> newDefaultInstance(
						mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_Feature_AttributesEntry_descriptor,
						com.google.protobuf.WireFormat.FieldType.STRING,
						"",
						com.google.protobuf.WireFormat.FieldType.STRING,
						"");
	}

	private com.google.protobuf.MapField<java.lang.String, java.lang.String> attributes_;

	private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetAttributes() {
		if (attributes_ == null) {
			return com.google.protobuf.MapField.emptyMapField(AttributesDefaultEntryHolder.defaultEntry);
		}
		return attributes_;
	}

	public int getAttributesCount() {
		return internalGetAttributes().getMap().size();
	}

	/**
	 * <code>map&lt;string, string&gt; attributes = 1;</code>
	 */

	public boolean containsAttributes(
			java.lang.String key ) {
		if (key == null) {
			throw new java.lang.NullPointerException();
		}
		return internalGetAttributes().getMap().containsKey(
				key);
	}

	/**
	 * Use {@link #getAttributesMap()} instead.
	 */
	@java.lang.Deprecated
	public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
		return getAttributesMap();
	}

	/**
	 * <code>map&lt;string, string&gt; attributes = 1;</code>
	 */

	public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
		return internalGetAttributes().getMap();
	}

	/**
	 * <code>map&lt;string, string&gt; attributes = 1;</code>
	 */

	public java.lang.String getAttributesOrDefault(
			java.lang.String key,
			java.lang.String defaultValue ) {
		if (key == null) {
			throw new java.lang.NullPointerException();
		}
		java.util.Map<java.lang.String, java.lang.String> map = internalGetAttributes().getMap();
		return map.containsKey(key) ? map.get(key) : defaultValue;
	}

	/**
	 * <code>map&lt;string, string&gt; attributes = 1;</code>
	 */

	public java.lang.String getAttributesOrThrow(
			java.lang.String key ) {
		if (key == null) {
			throw new java.lang.NullPointerException();
		}
		java.util.Map<java.lang.String, java.lang.String> map = internalGetAttributes().getMap();
		if (!map.containsKey(key)) {
			throw new java.lang.IllegalArgumentException();
		}
		return map.get(key);
	}

	private byte memoizedIsInitialized = -1;

	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1) return true;
		if (isInitialized == 0) return false;

		memoizedIsInitialized = 1;
		return true;
	}

	public void writeTo(
			com.google.protobuf.CodedOutputStream output )
			throws java.io.IOException {
		for (java.util.Map.Entry<java.lang.String, java.lang.String> entry : internalGetAttributes()
				.getMap()
				.entrySet()) {
			com.google.protobuf.MapEntry<java.lang.String, java.lang.String> attributes = AttributesDefaultEntryHolder.defaultEntry
					.newBuilderForType()
					.setKey(
							entry.getKey())
					.setValue(
							entry.getValue())
					.build();
			output.writeMessage(
					1,
					attributes);
		}
	}

	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1) return size;

		size = 0;
		for (java.util.Map.Entry<java.lang.String, java.lang.String> entry : internalGetAttributes()
				.getMap()
				.entrySet()) {
			com.google.protobuf.MapEntry<java.lang.String, java.lang.String> attributes = AttributesDefaultEntryHolder.defaultEntry
					.newBuilderForType()
					.setKey(
							entry.getKey())
					.setValue(
							entry.getValue())
					.build();
			size += com.google.protobuf.CodedOutputStream.computeMessageSize(
					1,
					attributes);
		}
		memoizedSize = size;
		return size;
	}

	private static final long serialVersionUID = 0L;

	@java.lang.Override
	public boolean equals(
			final java.lang.Object obj ) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature)) {
			return super.equals(obj);
		}
		mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature other = (mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature) obj;

		boolean result = true;
		result = result && internalGetAttributes().equals(
				other.internalGetAttributes());
		return result;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptorForType().hashCode();
		if (!internalGetAttributes().getMap().isEmpty()) {
			hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
			hash = (53 * hash) + internalGetAttributes().hashCode();
		}
		hash = (29 * hash) + unknownFields.hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature parseFrom(
			com.google.protobuf.ByteString data )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(
				data,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature parseFrom(
			byte[] data )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature parseFrom(
			byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(
				data,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature parseFrom(
			java.io.InputStream input )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature parseFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature parseDelimitedFrom(
			java.io.InputStream input )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
				PARSER,
				input);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature parseDelimitedFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
				PARSER,
				input,
				extensionRegistry);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature parseFrom(
			com.google.protobuf.CodedInputStream input )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input);
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
				PARSER,
				input,
				extensionRegistry);
	}

	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature prototype ) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(
				prototype);
	}

	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(
			com.google.protobuf.GeneratedMessageV3.BuilderParent parent ) {
		Builder builder = new Builder(
				parent);
		return builder;
	}

	/**
	 * <pre>
	 * a feature in this case is just a map of string key value pairs
	 * </pre>
	 *
	 * Protobuf type {@code Feature}
	 */
	public static final class Builder extends
			com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:Feature)
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.FeatureOrBuilder
	{
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_Feature_descriptor;
		}

		@SuppressWarnings({
			"rawtypes"
		})
		protected com.google.protobuf.MapField internalGetMapField(
				int number ) {
			switch (number) {
				case 1:
					return internalGetAttributes();
				default:
					throw new RuntimeException(
							"Invalid map field number: " + number);
			}
		}

		@SuppressWarnings({
			"rawtypes"
		})
		protected com.google.protobuf.MapField internalGetMutableMapField(
				int number ) {
			switch (number) {
				case 1:
					return internalGetMutableAttributes();
				default:
					throw new RuntimeException(
							"Invalid map field number: " + number);
			}
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_Feature_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature.class,
							mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature.Builder.class);
		}

		// Construct using
		// mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent ) {
			super(
					parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
		}

		public Builder clear() {
			super.clear();
			internalGetMutableAttributes().clear();
			return this;
		}

		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.AdapterVectorQueryService.internal_static_Feature_descriptor;
		}

		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature getDefaultInstanceForType() {
			return mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature.getDefaultInstance();
		}

		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature build() {
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature buildPartial() {
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature result = new mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature(
					this);
			int from_bitField0_ = bitField0_;
			result.attributes_ = internalGetAttributes();
			result.attributes_.makeImmutable();
			onBuilt();
			return result;
		}

		public Builder clone() {
			return (Builder) super.clone();
		}

		public Builder setField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				Object value ) {
			return (Builder) super.setField(
					field,
					value);
		}

		public Builder clearField(
				com.google.protobuf.Descriptors.FieldDescriptor field ) {
			return (Builder) super.clearField(field);
		}

		public Builder clearOneof(
				com.google.protobuf.Descriptors.OneofDescriptor oneof ) {
			return (Builder) super.clearOneof(oneof);
		}

		public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index,
				Object value ) {
			return (Builder) super.setRepeatedField(
					field,
					index,
					value);
		}

		public Builder addRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				Object value ) {
			return (Builder) super.addRepeatedField(
					field,
					value);
		}

		public Builder mergeFrom(
				com.google.protobuf.Message other ) {
			if (other instanceof mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature) {
				return mergeFrom((mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature) other);
			}
			else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(
				mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature other ) {
			if (other == mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature.getDefaultInstance())
				return this;
			internalGetMutableAttributes().mergeFrom(
					other.internalGetAttributes());
			onChanged();
			return this;
		}

		public final boolean isInitialized() {
			return true;
		}

		public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(
						input,
						extensionRegistry);
			}
			catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature) e
						.getUnfinishedMessage();
				throw e.unwrapIOException();
			}
			finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private int bitField0_;

		private com.google.protobuf.MapField<java.lang.String, java.lang.String> attributes_;

		private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetAttributes() {
			if (attributes_ == null) {
				return com.google.protobuf.MapField.emptyMapField(AttributesDefaultEntryHolder.defaultEntry);
			}
			return attributes_;
		}

		private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetMutableAttributes() {
			onChanged();
			;
			if (attributes_ == null) {
				attributes_ = com.google.protobuf.MapField.newMapField(AttributesDefaultEntryHolder.defaultEntry);
			}
			if (!attributes_.isMutable()) {
				attributes_ = attributes_.copy();
			}
			return attributes_;
		}

		public int getAttributesCount() {
			return internalGetAttributes().getMap().size();
		}

		/**
		 * <code>map&lt;string, string&gt; attributes = 1;</code>
		 */

		public boolean containsAttributes(
				java.lang.String key ) {
			if (key == null) {
				throw new java.lang.NullPointerException();
			}
			return internalGetAttributes().getMap().containsKey(
					key);
		}

		/**
		 * Use {@link #getAttributesMap()} instead.
		 */
		@java.lang.Deprecated
		public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
			return getAttributesMap();
		}

		/**
		 * <code>map&lt;string, string&gt; attributes = 1;</code>
		 */

		public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
			return internalGetAttributes().getMap();
		}

		/**
		 * <code>map&lt;string, string&gt; attributes = 1;</code>
		 */

		public java.lang.String getAttributesOrDefault(
				java.lang.String key,
				java.lang.String defaultValue ) {
			if (key == null) {
				throw new java.lang.NullPointerException();
			}
			java.util.Map<java.lang.String, java.lang.String> map = internalGetAttributes().getMap();
			return map.containsKey(key) ? map.get(key) : defaultValue;
		}

		/**
		 * <code>map&lt;string, string&gt; attributes = 1;</code>
		 */

		public java.lang.String getAttributesOrThrow(
				java.lang.String key ) {
			if (key == null) {
				throw new java.lang.NullPointerException();
			}
			java.util.Map<java.lang.String, java.lang.String> map = internalGetAttributes().getMap();
			if (!map.containsKey(key)) {
				throw new java.lang.IllegalArgumentException();
			}
			return map.get(key);
		}

		public Builder clearAttributes() {
			getMutableAttributes().clear();
			return this;
		}

		/**
		 * <code>map&lt;string, string&gt; attributes = 1;</code>
		 */

		public Builder removeAttributes(
				java.lang.String key ) {
			if (key == null) {
				throw new java.lang.NullPointerException();
			}
			getMutableAttributes().remove(
					key);
			return this;
		}

		/**
		 * Use alternate mutation accessors instead.
		 */
		@java.lang.Deprecated
		public java.util.Map<java.lang.String, java.lang.String> getMutableAttributes() {
			return internalGetMutableAttributes().getMutableMap();
		}

		/**
		 * <code>map&lt;string, string&gt; attributes = 1;</code>
		 */
		public Builder putAttributes(
				java.lang.String key,
				java.lang.String value ) {
			if (key == null) {
				throw new java.lang.NullPointerException();
			}
			if (value == null) {
				throw new java.lang.NullPointerException();
			}
			getMutableAttributes().put(
					key,
					value);
			return this;
		}

		/**
		 * <code>map&lt;string, string&gt; attributes = 1;</code>
		 */

		public Builder putAllAttributes(
				java.util.Map<java.lang.String, java.lang.String> values ) {
			getMutableAttributes().putAll(
					values);
			return this;
		}

		public final Builder setUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields ) {
			return this;
		}

		public final Builder mergeUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields ) {
			return this;
		}

		// @@protoc_insertion_point(builder_scope:Feature)
	}

	// @@protoc_insertion_point(class_scope:Feature)
	private static final mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature();
	}

	public static mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<Feature> PARSER = new com.google.protobuf.AbstractParser<Feature>() {
		public Feature parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return new Feature(
					input,
					extensionRegistry);
		}
	};

	public static com.google.protobuf.Parser<Feature> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<Feature> getParserForType() {
		return PARSER;
	}

	public mil.nga.giat.geowave.grpc.adapter.vector.query.protobuf.Feature getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
